{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.4.1.aar",
          "url": "databinding-adapters-8.4.1.aar",
          "size": 70404,
          "sha512": "98926c115573960e12b4929f3970967d5be7035598a9fdfc3d0ff35119f37ab450e6662c4d556204d75ceb8d07b657dae4634904bed3a0ee12c8bd8326b43284",
          "sha256": "af1a7130f000874d7933dd3081e74b0dc78d0b8101fd4f425b33c60713cab941",
          "sha1": "fe22bd08d28173dda32bb38cc4e1d903c6326cb1",
          "md5": "4a2dfc2c646544c40946389546c0e581"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-8.4.1.aar",
          "url": "databinding-adapters-8.4.1.aar",
          "size": 70404,
          "sha512": "98926c115573960e12b4929f3970967d5be7035598a9fdfc3d0ff35119f37ab450e6662c4d556204d75ceb8d07b657dae4634904bed3a0ee12c8bd8326b43284",
          "sha256": "af1a7130f000874d7933dd3081e74b0dc78d0b8101fd4f425b33c60713cab941",
          "sha1": "fe22bd08d28173dda32bb38cc4e1d903c6326cb1",
          "md5": "4a2dfc2c646544c40946389546c0e581"
        }
      ]
    }
  ]
}
