{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-device-provider-gradle",
    "version": "31.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.4.1.jar",
          "url": "android-device-provider-gradle-31.4.1.jar",
          "size": 50159,
          "sha512": "65efccfb0e8d3468fc8a4950578674921115e1450cbcb249790820f190d2be6fbe85d8cd605ae8a8107ec348a2b68fe8c96b87de87884b64324ef858f724b758",
          "sha256": "dea40b48ee3aef01cdd9fc4d71e34f07cbb9e510d8573fe884b9af1500586948",
          "sha1": "4141226924da17e36f57d0d4c1cf1e34d10b2515",
          "md5": "c688ae480be7891e8fae3c64ed31f8b3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-device-provider-gradle-proto",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "core-proto",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-device-provider-gradle-31.4.1.jar",
          "url": "android-device-provider-gradle-31.4.1.jar",
          "size": 50159,
          "sha512": "65efccfb0e8d3468fc8a4950578674921115e1450cbcb249790820f190d2be6fbe85d8cd605ae8a8107ec348a2b68fe8c96b87de87884b64324ef858f724b758",
          "sha256": "dea40b48ee3aef01cdd9fc4d71e34f07cbb9e510d8573fe884b9af1500586948",
          "sha1": "4141226924da17e36f57d0d4c1cf1e34d10b2515",
          "md5": "c688ae480be7891e8fae3c64ed31f8b3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.4.1-javadoc.jar",
          "url": "android-device-provider-gradle-31.4.1-javadoc.jar",
          "size": 261,
          "sha512": "79169aca5eb8b401e14c2f3eae5f822f86ffd83ef16d7072b7cc91e4f0179643ce943d22abe6937b2d8c56d70c9f6d384ff7c03372054a7220946efc3b00b90a",
          "sha256": "2aaaa83ca50623f70695830fd712003696199163764aa6a752828f3b17cc9386",
          "sha1": "7eebad25b6660e84ae98c53000b514b8cf7256e7",
          "md5": "e4b5ecd445930381347d7bd8677c7270"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-device-provider-gradle-31.4.1-sources.jar",
          "url": "android-device-provider-gradle-31.4.1-sources.jar",
          "size": 14103,
          "sha512": "d4fd17cc33894dfb6e501511c64112a2dec57ae09f37c0f9352140fb7e4a3e038327ed6eaf5ecba7b441a1304874d81f4e8779998a437d5cc306ecaa6e0bda12",
          "sha256": "8903baf1a7897ccf02f9b95bc6a673fc15d8cfaaf60bbac21b53db843306863d",
          "sha1": "3aa15163143354ed08bf651efd512e42fbca00a5",
          "md5": "3ac55476efd70f4508f5bbefbe806f58"
        }
      ]
    }
  ]
}
