{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "android-test-plugin-host-logcat",
    "version": "31.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.4.1.jar",
          "url": "android-test-plugin-host-logcat-31.4.1.jar",
          "size": 17756,
          "sha512": "6ae61fb5960d7352242fca5f0e0d05e76d138717c75e8a59b6a0a8b0574b1534beaf96cd49827f340e359e5f29f0d185890a6cd6a51c34098575cc8bd91a8b81",
          "sha256": "80b634bcf76e50497704da7e2281a96d3725bdc657dfbe252edf3897c5990f76",
          "sha1": "a288374deff2d38875c773e5a68c0c69171df368",
          "md5": "aef35e1459ca747ae705b96a6f711b7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "utp-common",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "android-test-plugin-host-logcat-proto",
          "version": {
            "requires": "31.4.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.google.testing.platform",
          "module": "android-device-provider-local",
          "version": {
            "requires": "0.0.9-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.4.1.jar",
          "url": "android-test-plugin-host-logcat-31.4.1.jar",
          "size": 17756,
          "sha512": "6ae61fb5960d7352242fca5f0e0d05e76d138717c75e8a59b6a0a8b0574b1534beaf96cd49827f340e359e5f29f0d185890a6cd6a51c34098575cc8bd91a8b81",
          "sha256": "80b634bcf76e50497704da7e2281a96d3725bdc657dfbe252edf3897c5990f76",
          "sha1": "a288374deff2d38875c773e5a68c0c69171df368",
          "md5": "aef35e1459ca747ae705b96a6f711b7a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.4.1-javadoc.jar",
          "url": "android-test-plugin-host-logcat-31.4.1-javadoc.jar",
          "size": 261,
          "sha512": "e45b175668fa8555d9207248b321010a8405d846901c1f7665a3409c528742b6207952c0f5fcf3b71e9cf14a36f7bb61e2f17bda94a409afd83f646fbe747d31",
          "sha256": "85464442e32beaba0fd6cf55d0e579bdf627399c10b4a151d543d8f347fdf00c",
          "sha1": "5ba48b0fd895389d2da19a4af87649e930c0f552",
          "md5": "be1428bdac190ee6ecdb3a40318d46eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android-test-plugin-host-logcat-31.4.1-sources.jar",
          "url": "android-test-plugin-host-logcat-31.4.1-sources.jar",
          "size": 5348,
          "sha512": "348a0eef1fbd686a56e769660085e37371b283264a78dee96c1d972b51f57a0124c6c6b04cb4c1fad80d9b94e3deca049e168e9971c1bf6400e47bb302fc1ec7",
          "sha256": "7e3886a412790e73b44925e5f99a8b325e4629bf0cb252e5ea0a4bb479ae844f",
          "sha1": "ce08c39af6c1e2cd4d39231a6e4f24e0a2e84830",
          "md5": "66ebb9b9f2ea8cde7be64b90c5e27296"
        }
      ]
    }
  ]
}
