{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.databinding",
    "module": "viewbinding",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "26.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.4.1.aar",
          "url": "viewbinding-8.4.1.aar",
          "size": 1867,
          "sha512": "d6cbbb548ad4131b4ea2d2d3bcfef0d589faf6de4aa2466a4a481359ab320ffe1c24c6366eaa6ffdf7fc1723c111684ffb1a43d15cad3ea2789e2b6ee2fb80b5",
          "sha256": "6e29d31a7c3d5bae460983367b8e039785a573e5757dc23d03205505d9be4ba9",
          "sha1": "718c175490de5187cea08d3b64be15dca3df3ba3",
          "md5": "10e0d5a941363da5a1b90a59228b21c1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "26.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewbinding-8.4.1.aar",
          "url": "viewbinding-8.4.1.aar",
          "size": 1867,
          "sha512": "d6cbbb548ad4131b4ea2d2d3bcfef0d589faf6de4aa2466a4a481359ab320ffe1c24c6366eaa6ffdf7fc1723c111684ffb1a43d15cad3ea2789e2b6ee2fb80b5",
          "sha256": "6e29d31a7c3d5bae460983367b8e039785a573e5757dc23d03205505d9be4ba9",
          "sha1": "718c175490de5187cea08d3b64be15dca3df3ba3",
          "md5": "10e0d5a941363da5a1b90a59228b21c1"
        }
      ]
    }
  ]
}
