{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-runtime",
    "version": "8.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.4.1.aar",
          "url": "databinding-runtime-8.4.1.aar",
          "size": 60873,
          "sha512": "2cb805a4f0bde9313936d3b6831e2f864f8cd01673fed28da9a57c7d85607afa30013ad0bd3e3e644cf07bb22905a8d58771622d93f9e75a033379e8f5a52a9a",
          "sha256": "52e11afbb560a0aecbe11ed7820c414e9d1d0e69e779fc61c45d9210d465f169",
          "sha1": "5aa8b51590debace9e6109c965ccee7275a80930",
          "md5": "aa264f678b22d9f99e7fc0505458f36b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-runtime-8.4.1.aar",
          "url": "databinding-runtime-8.4.1.aar",
          "size": 60873,
          "sha512": "2cb805a4f0bde9313936d3b6831e2f864f8cd01673fed28da9a57c7d85607afa30013ad0bd3e3e644cf07bb22905a8d58771622d93f9e75a033379e8f5a52a9a",
          "sha256": "52e11afbb560a0aecbe11ed7820c414e9d1d0e69e779fc61c45d9210d465f169",
          "sha1": "5aa8b51590debace9e6109c965ccee7275a80930",
          "md5": "aa264f678b22d9f99e7fc0505458f36b"
        }
      ]
    }
  ]
}
