# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: macos-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Execute Gradle commands in GitHub Actions workflows      
      - name: Execute gradle build
        run: ./gradlew build
        
      # Execute the clean managed devices to avoid lack of disk space for emulator snapshot
      - name: Execute Clean Managed Devices
        run: ./gradlew app:cleanManagedDevices --info
        
      #Execute Gradle managed device commands
      #- name: GMD device1 setup
      #  run: ./gradlew -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" app:device1Setup --info
        
      #Execute Gradle managed device commands
      - name: GMD device2 setup 
        run: ./gradlew -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" app:device2Setup --info
      
      #Execute the all tests on project
      - name: Exeuting tests on all devices 
        run : ./gradlew -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" app:allDevicesDebugAndroidTest --info
