# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  gradle:
    runs-on: macos-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

     
